import {
  siAnthropic,
  siApacheairflow,
  siApachespark,
  siCloudflare,
  siDocker,
  siDrizzle,
  siDuckdb,
  siFastapi,
  siFigma,
  siFramer,
  siGit,
  siGithub,
  siGithubactions,
  siGooglecloud,
  siGooglegemini,
  siGrafana,
  siGraphql,
  siHuggingface,
  siJupyter,
  siKubernetes,
  siLangchain,
  siLanggraph,
  siLinear,
  siLinux,
  siNextdotjs,
  siNodedotjs,
  siNumpy,
  siOllama,
  siPandas,
  siPlotly,
  siPostgresql,
  siPrisma,
  siPython,
  siPytorch,
  siR,
  siReact,
  siRedis,
  siScikitlearn,
  siSentry,
  siStorybook,
  siSupabase,
  siTailwindcss,
  siTerraform,
  siThreedotjs,
  siTrpc,
  siTypescript,
  siVercel,
  siVite,
  siWebgl,
  siZod,
} from "simple-icons";

export type BrandIcon = { title: string; path: string; hex: string };

/**
 * Brand icons pulled from the `simple-icons` package (tree-shaken named imports).
 * Icons that simple-icons no longer ships (e.g. OpenAI, AWS) fall back to a
 * monogram tile in <TechIcon />.
 */
export const brandIcons: Record<string, BrandIcon> = {
  anthropic: siAnthropic,
  apacheairflow: siApacheairflow,
  apachespark: siApachespark,
  cloudflare: siCloudflare,
  docker: siDocker,
  drizzle: siDrizzle,
  duckdb: siDuckdb,
  fastapi: siFastapi,
  figma: siFigma,
  framer: siFramer,
  git: siGit,
  github: siGithub,
  githubactions: siGithubactions,
  googlecloud: siGooglecloud,
  googlegemini: siGooglegemini,
  grafana: siGrafana,
  graphql: siGraphql,
  huggingface: siHuggingface,
  jupyter: siJupyter,
  kubernetes: siKubernetes,
  langchain: siLangchain,
  langgraph: siLanggraph,
  linear: siLinear,
  linux: siLinux,
  nextdotjs: siNextdotjs,
  nodedotjs: siNodedotjs,
  numpy: siNumpy,
  ollama: siOllama,
  pandas: siPandas,
  plotly: siPlotly,
  postgresql: siPostgresql,
  prisma: siPrisma,
  python: siPython,
  pytorch: siPytorch,
  r: siR,
  react: siReact,
  redis: siRedis,
  scikitlearn: siScikitlearn,
  sentry: siSentry,
  storybook: siStorybook,
  supabase: siSupabase,
  tailwindcss: siTailwindcss,
  terraform: siTerraform,
  threedotjs: siThreedotjs,
  trpc: siTrpc,
  typescript: siTypescript,
  vercel: siVercel,
  vite: siVite,
  webgl: siWebgl,
  zod: siZod,
  // LinkedIn is no longer distributed by simple-icons; path reproduced here.
  linkedin: {
    title: "LinkedIn",
    hex: "0A66C2",
    path: "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z",
  },
};

export function getBrandIcon(key?: string): BrandIcon | undefined {
  if (!key) return undefined;
  return brandIcons[key];
}

/** Map a human stack label (e.g. "Next.js") to a brand icon key. */
const stackAliases: Record<string, string> = {
  "next.js": "nextdotjs",
  nextjs: "nextdotjs",
  react: "react",
  typescript: "typescript",
  python: "python",
  fastapi: "fastapi",
  postgresql: "postgresql",
  postgres: "postgresql",
  redis: "redis",
  docker: "docker",
  kubernetes: "kubernetes",
  vercel: "vercel",
  "tailwind css": "tailwindcss",
  tailwind: "tailwindcss",
  "three.js": "threedotjs",
  motion: "framer",
  langgraph: "langgraph",
  langchain: "langchain",
  zod: "zod",
  prisma: "prisma",
  "node.js": "nodedotjs",
  node: "nodedotjs",
  supabase: "supabase",
  plotly: "plotly",
  "google cloud": "googlecloud",
  terraform: "terraform",
  cloudflare: "cloudflare",
  "github actions": "githubactions",
  grafana: "grafana",
  sentry: "sentry",
  linux: "linux",
  jupyter: "jupyter",
  pandas: "pandas",
  numpy: "numpy",
  "scikit-learn": "scikitlearn",
  pytorch: "pytorch",
  "hugging face": "huggingface",
  ollama: "ollama",
  vite: "vite",
  storybook: "storybook",
  graphql: "graphql",
  trpc: "trpc",
  drizzle: "drizzle",
  duckdb: "duckdb",
  "apache spark": "apachespark",
  airflow: "apacheairflow",
  figma: "figma",
  linear: "linear",
  git: "git",
  github: "github",
  webgl: "webgl",
  r: "r",
  anthropic: "anthropic",
  gemini: "googlegemini",
};

export function iconKeyForStack(label: string): string | undefined {
  return stackAliases[label.toLowerCase()];
}

export function iconForStack(label: string) {
  return getBrandIcon(iconKeyForStack(label));
}
